// Emits the committed JSON Schemas for non-JS clients (Guide B9, Invariant I7).
// Generated output — never hand-edit schemas/*.json; re-run `npm run protocol:emit`.
// Run after `tsc -b` (imports the built dist/).
import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { z } from 'zod';
import {
  AdvanceTimeAcceptedSchema,
  AdvanceTimeCommandSchema,
  ApplyUpdateAcceptedSchema,
  ApplyUpdateCommandSchema,
  CommandRejectedSchema,
  DeleteProfileAcceptedSchema,
  DeleteProfileCommandSchema,
  DevEventSchema,
  EndSceneAcceptedSchema,
  EndSceneCommandSchema,
  ExitChatAcceptedSchema,
  ExitChatCommandSchema,
  ExitGroupChatAcceptedSchema,
  ExitGroupChatCommandSchema,
  ExploreAcceptedSchema,
  ExploreCommandSchema,
  FeedReplyAcceptedSchema,
  FeedReplyCommandSchema,
  InterruptTurnAcceptedSchema,
  InterruptTurnCommandSchema,
  MapClickAcceptedSchema,
  MapClickCommandSchema,
  MapEditAcceptedSchema,
  MapEditCommandSchema,
  MapJumpDetailSchema,
  OpenSceneAcceptedSchema,
  OpenSceneCommandSchema,
  PaintRegionAcceptedSchema,
  PaintRegionCommandSchema,
  PluginListSchema,
  ResolveProposalAcceptedSchema,
  ResolveProposalCommandSchema,
  SendChatMessageAcceptedSchema,
  SendChatMessageCommandSchema,
  SetCharacterLockAcceptedSchema,
  SetCharacterLockCommandSchema,
  SetConfigFlagAcceptedSchema,
  SetConfigFlagCommandSchema,
  SendGroupMessageAcceptedSchema,
  SendGroupMessageCommandSchema,
  StartGroupChatAcceptedSchema,
  StartGroupChatCommandSchema,
  StartSceneFromChatAcceptedSchema,
  StartSceneFromChatCommandSchema,
  StartTurnAcceptedSchema,
  StartTurnCommandSchema,
  SubwikiEditAcceptedSchema,
  SubwikiEditCommandSchema,
  StreamHelloSchema,
  StreamSentenceSchema,
  WeltariEventSchema,
} from '../dist/index.js';

const outDir = join(import.meta.dirname, '..', 'schemas');
await mkdir(outDir, { recursive: true });

const files = {
  'weltari-event.json': WeltariEventSchema,
  'stream-hello.json': StreamHelloSchema,
  'stream-sentence.json': StreamSentenceSchema,
  'dev-event.json': DevEventSchema,
  'start-turn-command.json': StartTurnCommandSchema,
  'start-turn-accepted.json': StartTurnAcceptedSchema,
  'end-scene-command.json': EndSceneCommandSchema,
  'end-scene-accepted.json': EndSceneAcceptedSchema,
  'interrupt-turn-command.json': InterruptTurnCommandSchema,
  'interrupt-turn-accepted.json': InterruptTurnAcceptedSchema,
  'open-scene-command.json': OpenSceneCommandSchema,
  'open-scene-accepted.json': OpenSceneAcceptedSchema,
  'explore-command.json': ExploreCommandSchema,
  'explore-accepted.json': ExploreAcceptedSchema,
  'advance-time-command.json': AdvanceTimeCommandSchema,
  'advance-time-accepted.json': AdvanceTimeAcceptedSchema,
  'paint-region-command.json': PaintRegionCommandSchema,
  'paint-region-accepted.json': PaintRegionAcceptedSchema,
  'map-edit-command.json': MapEditCommandSchema,
  'map-edit-accepted.json': MapEditAcceptedSchema,
  'map-click-command.json': MapClickCommandSchema,
  'map-click-accepted.json': MapClickAcceptedSchema,
  'apply-update-command.json': ApplyUpdateCommandSchema,
  'apply-update-accepted.json': ApplyUpdateAcceptedSchema,
  'send-chat-message-command.json': SendChatMessageCommandSchema,
  'send-chat-message-accepted.json': SendChatMessageAcceptedSchema,
  'start-group-chat-command.json': StartGroupChatCommandSchema,
  'start-group-chat-accepted.json': StartGroupChatAcceptedSchema,
  'send-group-message-command.json': SendGroupMessageCommandSchema,
  'send-group-message-accepted.json': SendGroupMessageAcceptedSchema,
  'exit-group-chat-command.json': ExitGroupChatCommandSchema,
  'exit-group-chat-accepted.json': ExitGroupChatAcceptedSchema,
  'exit-chat-command.json': ExitChatCommandSchema,
  'exit-chat-accepted.json': ExitChatAcceptedSchema,
  'start-scene-from-chat-command.json': StartSceneFromChatCommandSchema,
  'start-scene-from-chat-accepted.json': StartSceneFromChatAcceptedSchema,
  'feed-reply-command.json': FeedReplyCommandSchema,
  'feed-reply-accepted.json': FeedReplyAcceptedSchema,
  'subwiki-edit-command.json': SubwikiEditCommandSchema,
  'subwiki-edit-accepted.json': SubwikiEditAcceptedSchema,
  'resolve-proposal-command.json': ResolveProposalCommandSchema,
  'resolve-proposal-accepted.json': ResolveProposalAcceptedSchema,
  'set-config-flag-command.json': SetConfigFlagCommandSchema,
  'set-config-flag-accepted.json': SetConfigFlagAcceptedSchema,
  'set-character-lock-command.json': SetCharacterLockCommandSchema,
  'set-character-lock-accepted.json': SetCharacterLockAcceptedSchema,
  'delete-profile-command.json': DeleteProfileCommandSchema,
  'delete-profile-accepted.json': DeleteProfileAcceptedSchema,
  'command-rejected.json': CommandRejectedSchema,
  'plugin-list.json': PluginListSchema,
  'map-jump-detail.json': MapJumpDetailSchema,
};

for (const [name, schema] of Object.entries(files)) {
  const jsonSchema = z.toJSONSchema(schema, { target: 'draft-2020-12' });
  await writeFile(
    join(outDir, name),
    `${JSON.stringify(jsonSchema, null, 2)}\n`,
    'utf8',
  );
}
console.log(
  `emitted ${Object.keys(files).length} schemas to packages/protocol/schemas/`,
);
